const surpriseMePrompts = ['A futuristic cityscape with towering skyscrapers and flying vehicles.',
'Exploring an alien planet with breathtaking landscapes and unique flora.',
'A thrilling space battle among the stars.',
'A serene garden on a distant moon with exotic plants and colorful wildlife.',
'Journeying through a time portal to a post-apocalyptic world.',
'A picturesque waterfall cascading down a cliff in a hidden forest.',
'Unraveling the mysteries of a derelict spaceship drifting in space.',
'A peaceful floating island in the sky with magnificent floating gardens.',
'A thrilling chase through a cyberpunk city illuminated by neon lights.',
'Adventuring through a virtual reality simulation of ancient civilizations.',
'A secret underground laboratory filled with futuristic technology.',
'An expansive desert with towering sand dunes stretching into the horizon.',
'Surviving on a space station during a catastrophic solar storm.',
'A dense jungle teeming with exotic creatures and hidden ancient ruins.',
'A high-tech laboratory where cutting-edge experiments are conducted.',
'Witnessing a breathtaking meteor shower from a remote mountaintop.',
'A dystopian cityscape ruled by advanced artificial intelligence.',
'Discovering a hidden portal that leads to parallel dimensions.',
'An underwater city filled with colorful marine life and advanced architecture.',
'A peaceful countryside village surrounded by rolling hills and farmland.',
'Exploring a mysterious abandoned spaceship drifting in deep space.',
'A majestic space station orbiting a distant planet.',
'A tranquil beach with crystal-clear waters and vibrant coral reefs.',
'A futuristic society where humans coexist with advanced robots.',
'Navigating a labyrinthine maze with futuristic technology.',
'A stunning aurora borealis lighting up the night sky over a snowy landscape.',
'Encountering extraterrestrial life on a distant alien planet.',
'A bustling intergalactic marketplace filled with diverse species.',
'A futuristic city submerged underwater with advanced aquatic technology.',
'Embarking on a perilous expedition to a frozen, unexplored continent.',
'A post-apocalyptic wasteland with remnants of advanced technology.',
'A remote space colony struggling to survive in hostile surroundings.',
'A magnificent floating city above the clouds with breathtaking views.',
'A mysterious artifact with the power to alter reality.',
'An ancient temple hidden deep within a dense jungle.',
'A space exploration mission to discover new habitable planets.',
'A futuristic train traversing through breathtaking landscapes at high speeds.',
'An underground resistance fighting against a tyrannical regime.',
'A journey through a wormhole to reach a distant galaxy.',
'A floating spaceship graveyard filled with remnants of past space battles.',
'A high-tech metropolis where virtual reality and physical reality merge.',
'A vast underground cavern with bioluminescent flora and fauna.',
'Exploring the ruins of an ancient civilization on a distant planet.',
'A thrilling chase through a zero-gravity space station.',
'A futuristic society where dreams can be experienced and shared.',
'A remote research outpost in the Arctic, studying the effects of climate change.',
'A parallel universe where magic and advanced technology coexist.',
'A magnificent starship traveling through a wormhole to another galaxy.',
'Two galaxies colliding into one.',
'A intergalactic alien space war between two different species of beings.'];

module.exports = surpriseMePrompts;
